export const projects = [
  {
    id: 1,
    title: "Stone Mind",
    category: "AI Automation",
    description:
      "An intelligent workflow automation system that transforms repetitive business processes into seamless, self-running pipelines.",
    year: "2024",
    tags: ["AI", "Automation", "Python"],
    image: "/project-1.svg",
    featured: true,
  },
  {
    id: 2,
    title: "Violet Orbit",
    category: "Web Development",
    description:
      "A modern SaaS dashboard built for real-time data visualization and team collaboration at scale.",
    year: "2024",
    tags: ["Next.js", "TypeScript", "Tailwind"],
    image: "/project-2.svg",
    featured: true,
  },
  {
    id: 3,
    title: "Pulse CRM",
    category: "Full Stack",
    description:
      "A lightweight CRM system with AI-powered lead scoring and automated follow-up sequences.",
    year: "2023",
    tags: ["React", "Node.js", "OpenAI"],
    image: "/project-3.svg",
    featured: true,
  },
  {
    id: 4,
    title: "Echo Bot",
    category: "AI Automation",
    description:
      "A conversational AI assistant integrated across Slack, WhatsApp, and email for unified team communication.",
    year: "2023",
    tags: ["LLM", "Bots", "API Integration"],
    image: "/project-4.svg",
    featured: true,
  },
  {
    id: 5,
    title: "Flux Analytics",
    category: "Data",
    description:
      "A real-time analytics pipeline that ingests, processes, and surfaces actionable insights from raw event streams.",
    year: "2023",
    tags: ["Python", "Data", "Dashboard"],
    image: "/project-3.svg",
    featured: false,
  },
];

export const socials = [
  { label: "Linkedin", href: "https://linkedin.com" },
  { label: "Twitter", href: "https://twitter.com" },
  { label: "Behance", href: "https://behance.net" },
];

export const email = "maryam@zamoog.com";

export const industries = [
  {
    slug: "digital-marketing-agencies",
    title: "Digital Marketing Agencies",
    subNiches: [
      "Agencies",
      "Consultants",
      "Freelancers",
      "In-house",
      "Growth",
      "Performance",
      "Content",
      "SEO",
      "PPC",
      "Social",
    ],
    painPoints: [
      "Leads slip through cracks without follow-up",
      "Manual outreach wastes hours of staff time",
      "No system to nurture cold prospects",
      "Client reporting is tedious and delayed",
      "Campaign data scattered across platforms",
      "Can't scale without hiring more people",
    ],
    solutions: [
      "AI follows up with cold prospects automatically via email and LinkedIn",
      "Send personalized messages to 1000s of prospects without manual work",
      "Auto-generate reports from all platforms and send to clients weekly",
      "AI ranks leads by quality so your team focuses on hot prospects only",
    ],
    automations: [
      "Clay outreach workflows that run 24/7",
      "LinkedIn automation for mass prospecting",
      "Email nurture sequences that feel personal",
      "Lead scoring based on engagement",
    ],
  },
  {
    slug: "real-estate",
    title: "Real Estate & Home Services",
    subNiches: [
      "Agents",
      "Brokers",
      "Developers",
      "Contractors",
      "Plumbers",
      "Electricians",
      "HVAC",
      "Handyman",
      "Landscaping",
      "Cleaning",
    ],
    painPoints: [
      "Properties sit listed without follow-up",
      "Missed calls from interested buyers",
      "No automated showing reminders",
      "Lead follow-up is inconsistent",
      "Competitors respond faster to inquiries",
      "Client communication falls through cracks",
    ],
    solutions: [
      "AI answers calls 24/7, qualifies buyers, books showings automatically",
      "Auto-SMS reminders to buyers before showings reduce no-shows by 40%",
      "Auto-nurture prospects with property updates and personalized messages",
      "Answer buyer questions instantly, schedule tours without manual work",
    ],
    automations: [
      "Inbound call handling with AI agents",
      "WhatsApp chatbot for property inquiries",
      "Showing reminders via SMS",
      "Lead follow-up sequences",
    ],
  },
  {
    slug: "e-commerce",
    title: "E-Commerce",
    subNiches: [
      "Amazon",
      "Shopify",
      "Dropshipping",
      "Wholesale",
      "Marketplace",
      "B2C",
      "Retail",
      "Fashion",
      "Electronics",
      "Niche",
    ],
    painPoints: [
      "Inventory changes manually across platforms",
      "Competitors undercut prices but you don't know",
      "Customer inquiries answered slowly",
      "No automated reorder reminders",
      "Refunds and returns handled manually",
      "Product listings outdated on multiple sites",
    ],
    solutions: [
      "Auto-track competitor prices and alert you when you're undercut",
      "Update inventory across all platforms in real-time, zero manual work",
      "AI answers product questions, processes returns, handles complaints",
      "Auto-remind customers of past purchases to boost repeat sales",
    ],
    automations: [
      "Price monitoring and competitor tracking",
      "Inventory sync across marketplaces",
      "Customer service chatbot",
      "Reorder reminder campaigns",
    ],
  },
  {
    slug: "saas",
    title: "SaaS",
    subNiches: [
      "Founders",
      "Startups",
      "B2B",
      "Productivity",
      "Analytics",
      "CRM",
      "Marketplace",
      "Tools",
      "Platforms",
      "Enterprise",
    ],
    painPoints: [
      "Leads stuck in pipeline with no follow-up",
      "Trial users don't get onboarded properly",
      "Churn happens because no one checks in",
      "Customer data scattered across tools",
      "Support tickets pile up unanswered",
      "Billing and payment reminders are manual",
    ],
    solutions: [
      "AI sequences nurture leads through sales pipeline automatically",
      "Auto-send onboarding videos, guides, and check-ins to trial users",
      "AI detects inactive users and auto-sends re-engagement campaigns",
      "AI handles common support tickets 24/7, escalates complex issues",
    ],
    automations: [
      "Lead nurture sequences",
      "Trial user onboarding flows",
      "Churn detection and prevention",
      "Support ticket automation",
    ],
  },
  {
    slug: "professional-services",
    title: "Professional Services",
    subNiches: [
      "Consultants",
      "Designers",
      "Developers",
      "Writers",
      "Copywriters",
      "Coaches",
      "Photographers",
      "Videographers",
      "Architects",
      "Engineers",
    ],
    painPoints: [
      "Client proposals take forever to send",
      "Follow-up on quotes is inconsistent",
      "Contracts and documents managed manually",
      "Invoice reminders are forgotten",
      "Client communication is disorganized",
      "Time tracking and billing are error-prone",
    ],
    solutions: [
      "Auto-generate and send professional proposals in minutes, not hours",
      "AI automatically follows up on pending quotes, increases close rate",
      "Auto-send payment reminders, reduce late payments and follow-ups",
      "Auto-organize contracts and files, send for e-signature automatically",
    ],
    automations: [
      "Proposal generation workflows",
      "Quote follow-up sequences",
      "Invoice reminder automation",
      "Document management and e-signature",
    ],
  },
  {
    slug: "healthcare-dental",
    title: "Healthcare & Dental",
    subNiches: [
      "Dentists",
      "Clinics",
      "Therapists",
      "Dermatologists",
      "Surgeons",
      "Pharmacies",
      "Hospitals",
      "Wellness",
      "Mental Health",
      "Pediatric",
    ],
    painPoints: [
      "Patients forget appointments and don't show",
      "Bad reviews scare away new patients",
      "Missed after-hours calls go to competitors",
      "No follow-up on treatment plans",
      "Patients disappear and never return",
      "Staff wastes time on manual reminders",
    ],
    solutions: [
      "WhatsApp reminders 24hrs before appointments cut no-shows in half",
      "Auto-collect reviews after visits, boost your Google rating",
      "AI answers calls after hours, schedules appointments automatically",
      "Auto-follow-up with treatment plans and payment options",
    ],
    automations: [
      "Appointment reminder system via WhatsApp/SMS",
      "Review collection and request automation",
      "After-hours inbound call handling",
      "Treatment plan follow-up sequences",
    ],
  },
  {
    slug: "beauty-fitness",
    title: "Beauty & Fitness",
    subNiches: [
      "Gyms",
      "Salons",
      "Spas",
      "Personal Trainers",
      "Yoga",
      "Studios",
      "Hair",
      "Makeup",
      "Wellness",
      "CrossFit",
    ],
    painPoints: [
      "Members cancel without being asked to stay",
      "Class bookings are chaos without a system",
      "No reminders so members forget sessions",
      "New member onboarding is weak",
      "Reviews aren't collected automatically",
      "Upsells and packages go unnoticed",
    ],
    solutions: [
      "AI reaches out before cancellation, saves memberships automatically",
      "Auto-manage class bookings, send confirmations and reminders",
      "SMS reminders reduce no-shows and boost attendance",
      "Auto-send onboarding flows to new members with intro classes",
    ],
    automations: [
      "Churn prevention workflows",
      "Class booking and confirmation system",
      "Member reminder automations",
      "New member onboarding sequences",
    ],
  },
  {
    slug: "accounting-law-insurance",
    title: "Accounting, Law & Insurance",
    subNiches: [
      "Accountants",
      "CPAs",
      "Lawyers",
      "Insurance Agents",
      "Tax",
      "Compliance",
      "Audit",
      "Legal",
      "Claims",
      "Policies",
    ],
    painPoints: [
      "Document requests take forever to process",
      "Clients miss important deadlines",
      "Invoice follow-ups are manual and forgotten",
      "Compliance reminders aren't automated",
      "New client onboarding is tedious",
      "Communication gaps cause missed opportunities",
    ],
    solutions: [
      "Auto-request documents, organize them, track completion status",
      "AI sends deadline reminders before important dates",
      "Auto-send invoices and payment reminders, reduce late payments",
      "Compliance check reminders for tax deadlines and filings",
    ],
    automations: [
      "Document request and collection workflows",
      "Deadline reminder system",
      "Invoice and payment automation",
      "Compliance calendar automation",
    ],
  },
  {
    slug: "hospitality-food",
    title: "Hospitality & Food",
    subNiches: [
      "Restaurants",
      "Cafes",
      "Hotels",
      "Catering",
      "Bars",
      "Bakeries",
      "Food Trucks",
      "Events",
      "Venues",
      "Resorts",
    ],
    painPoints: [
      "Reservations are missed or double-booked",
      "No-shows hurt revenue constantly",
      "Customer feedback isn't collected",
      "Repeat customers don't get special treatment",
      "Marketing campaigns are sent manually",
      "Staff scheduling is a nightmare",
    ],
    solutions: [
      "AI manages reservations, prevents double-booking, confirms bookings",
      "SMS reminders the day before cut no-shows significantly",
      "Auto-send review requests after each visit",
      "Auto-send loyalty offers to repeat customers",
    ],
    automations: [
      "Reservation management and confirmation",
      "No-show prevention reminders",
      "Review request automation",
      "Loyalty and repeat customer campaigns",
    ],
  },
  {
    slug: "education-coaching",
    title: "Education & Coaching",
    subNiches: [
      "Tutors",
      "Online Courses",
      "Bootcamps",
      "Life Coaches",
      "Business Coaches",
      "Language",
      "Music",
      "Fitness",
      "Mentoring",
      "Workshops",
    ],
    painPoints: [
      "Students miss classes with no reminder",
      "Payment reminders are forgotten",
      "Student progress tracking is manual",
      "New student onboarding is slow",
      "Upsells on courses aren't automated",
      "Communication with students is inconsistent",
    ],
    solutions: [
      "Auto-send class reminders, reduce no-shows and dropouts",
      "AI reminds students of upcoming payments, reduces churn",
      "Auto-track progress and send personalized feedback",
      "Automated onboarding sequence gets new students started fast",
    ],
    automations: [
      "Class reminder system",
      "Payment reminder workflows",
      "Progress tracking automation",
      "New student onboarding sequences",
    ],
  },
  {
    slug: "recruitment",
    title: "Recruitment & Staffing",
    subNiches: [
      "Recruiters",
      "Agencies",
      "HR",
      "Headhunters",
      "Tech Talent",
      "Executive",
      "Temp Staff",
      "Remote",
      "Freelance",
      "Contract",
    ],
    painPoints: [
      "Candidates go cold without follow-up",
      "Job postings don't get shared everywhere",
      "Interview scheduling is back-and-forth chaos",
      "Rejected candidates aren't notified",
      "Onboarding paperwork piles up",
      "You lose candidates to faster competitors",
    ],
    solutions: [
      "AI automatically follows up with candidates at each stage",
      "Job posts shared across LinkedIn, Indeed, and all platforms automatically",
      "AI coordinates interview scheduling, sends confirmations",
      "Auto-send rejection emails and keep candidates in pipeline",
    ],
    automations: [
      "Candidate follow-up sequences",
      "Job posting distribution automation",
      "Interview scheduling and confirmation",
      "Candidate relationship management",
    ],
  },
  {
    slug: "manufacturing-logistics",
    title: "Manufacturing & Logistics",
    subNiches: [
      "Manufacturers",
      "Warehousing",
      "Supply Chain",
      "Distribution",
      "Shipping",
      "Freight",
      "Ecommerce Fulfillment",
      "3PL",
      "Inventory",
      "Orders",
    ],
    painPoints: [
      "Inventory changes aren't synced in real time",
      "Orders get lost in manual processing",
      "Supplier communication is delayed",
      "Shipment tracking is fragmented",
      "Invoicing and payments are slow",
      "Data entry errors cause costly mistakes",
    ],
    solutions: [
      "Real-time inventory sync across all systems, no manual updates",
      "Auto-process orders, eliminate manual data entry errors",
      "Auto-send orders to suppliers and get status updates",
      "AI tracks shipments and alerts customers automatically",
    ],
    automations: [
      "Inventory sync automation",
      "Order processing workflows",
      "Supplier order and communication automation",
      "Shipment tracking and customer alerts",
    ],
  },
  {
    slug: "automotive",
    title: "Automotive Dealerships",
    subNiches: [
      "Dealerships",
      "Service Centers",
      "Used Cars",
      "New Cars",
      "Parts",
      "Mechanic Shops",
      "Detailing",
      "Rentals",
      "Leasing",
      "Trade-in",
    ],
    painPoints: [
      "Service appointment reminders aren't sent",
      "Leads from website inquiries go cold",
      "Test drive follow-ups are forgotten",
      "Customer service requests pile up",
      "Trade-in valuations are slow",
      "Repeat customers don't get contacted",
    ],
    solutions: [
      "SMS reminders for service appointments reduce no-shows",
      "AI immediately follows up with website leads, books test drives",
      "Auto-follow-up after test drives with personalized offers",
      "AI handles customer inquiries instantly via chatbot",
    ],
    automations: [
      "Service appointment reminder system",
      "Lead qualification and follow-up",
      "Test drive confirmation and follow-up",
      "Customer inquiry chatbot",
    ],
  },
  {
    slug: "others",
    title: "Others",
    subNiches: [
      "Construction",
      "Events",
      "Travel",
      "Nonprofits",
      "Creators",
      "Influencers",
      "Local Businesses",
      "Franchises",
      "Car Rentals",
      "Studios",
    ],
    painPoints: [
      "Too much repetitive admin work every day",
      "Customers wait too long for replies",
      "Leads are missed outside working hours",
      "Staff spends hours updating spreadsheets manually",
      "Bookings and inquiries are difficult to manage",
      "Business growth slows because operations are manual",
    ],
    solutions: [
      "AI replies instantly to customer questions 24/7",
      "Automatically organize inquiries, bookings and leads in one place",
      "Send reminders and follow-ups without manual work",
      "Reduce repetitive admin tasks that waste staff time",
      "Connect all your apps and systems together automatically",
      "Save hours every week by automating repetitive tasks",
    ],
    automations: [
      "WhatsApp and website chatbots",
      "Automatic booking and reminder systems",
      "Lead collection and follow-up workflows",
      "Custom business dashboards",
      "Spreadsheet and admin task automation",
      "App integrations and workflow automations",
    ],
  },
];

export const pricing = [
  {
    title: "WhatsApp Bots",
    price: "$200 – $300",
    desc: "Automatic replies for customers, bookings, FAQs and lead responses on WhatsApp.",
    advantage: "You won&apos;t have to reply to customers manually all day.",
  },

  {
    title: "CRM Automations",
    price: "$300 – $500",
    desc: "Automatic follow-ups, reminders and lead organization.",
    advantage: "You won&apos;t need to follow up with leads manually.",
  },

  {
    title: "Lead Capture Systems",
    price: "$350 – $500",
    desc: "Collect leads from ads, websites and forms automatically.",
    advantage: "You won&apos;t lose leads from missed messages or forms.",
  },

  {
    title: "Voice Calling Systems",
    price: "$300 – $500",
    desc: "AI phone callers for bookings, support and follow-ups.",
    advantage: "Your business can answer calls even when you&apos;re busy.",
  },

  {
    title: "Website Chatbots",
    price: "$200 – $300",
    desc: "Chatbots that answer customer questions instantly.",
    advantage: "Customers get replies instantly without waiting for staff.",
  },

  {
    title: "GoHighLevel Automations",
    price: "$300 – $600",
    desc: "Automatic texts, emails and reminders inside GHL.",
    advantage: "You won&apos;t have to send reminders or follow-ups manually.",
  },

  {
    title: "Cold Email Systems Setups",
    price: "$800 – $1,000",
    desc: "Automatic outreach emails with follow-ups.",
    advantage: "Reach more people without manually sending emails daily.",
  },

  {
    title: "LinkedIn Automations",
    price: "$250 – $400",
    desc: "Automatic LinkedIn outreach and messaging.",
    advantage:
      "You won&apos;t have to spend hours messaging prospects manually.",
  },

  {
    title: "Lead Research Workflows",
    price: "$300 – $1,500",
    desc: "Automatically find and organize potential customers.",
    advantage: "You won&apos;t waste time searching for leads manually.",
  },

  {
    title: "Content Posting Systems",
    price: "$400 – $1,000",
    desc: "Automatically create and post social media content.",
    advantage: "Your pages stay active without daily posting work.",
  },

  {
    title: "Custom Data Scrapers",
    price: "$200 – $600",
    desc: "Collect useful data from websites automatically.",
    advantage: "You won&apos;t have to copy and collect data manually.",
  },

  {
    title: "App Integrations",
    price: "$150 – $500",
    desc: "Connect your apps and tools together automatically.",
    advantage: "Your tools will work together without manual updates.",
  },

  {
    title: "Website Development",
    price: "$500 – $1,500+",
    desc: "Landing Pages, Funnels, SaaS.",
    advantage:
      "Your AI Builder apps isn&apos;t going to build a SaaS for you, trust me.",
  },
];

export function toSlug(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
