export const socials = [
  { label: "Maryam — LinkedIn", href: "https://www.linkedin.com/in/maryam-naveed-zamoog-n8n" },
  { label: "Maryam — Upwork", href: "https://www.upwork.com/freelancers/~01e1760bd58725f035" },
  { label: "Ali — LinkedIn", href: "https://www.linkedin.com/in/alizamankhanai/" },
  { label: "Ali — Upwork", href: "https://www.upwork.com/freelancers/~01150fb0db7338a9a5" },
];

export const email = "maryam@zamoog.com";
export const emailAli = "ali@zamoog.com";

export const industries = [
  {
    slug: "digital-marketing-agencies",
    title: "Digital Marketing Agencies",
    subNiches: [
      "Agencies",
      "Consultants",
      "Freelancers",
      "In-house",
      "Growth",
      "Performance",
      "Content",
      "SEO",
      "PPC",
      "Social",
    ],
    painPoints: [
      "Leads slip through cracks without follow-up",
      "Manual outreach wastes hours of staff time",
      "No system to nurture cold prospects",
      "Client reporting is tedious and delayed",
      "Campaign data scattered across platforms",
      "Can't scale without hiring more people",
    ],
    solutions: [
      "AI follows up with cold prospects automatically via email and LinkedIn",
      "Send personalized messages to 1000s of prospects without manual work",
      "Auto-generate reports from all platforms and send to clients weekly",
      "AI ranks leads by quality so your team focuses on hot prospects only",
    ],
    automations: [
      "Clay outreach workflows that run 24/7",
      "LinkedIn automation for mass prospecting",
      "Email nurture sequences that feel personal",
      "Lead scoring based on engagement",
    ],
  },
  {
    slug: "real-estate",
    title: "Real Estate & Home Services",
    subNiches: [
      "Agents",
      "Brokers",
      "Developers",
      "Contractors",
      "Plumbers",
      "Electricians",
      "HVAC",
      "Handyman",
      "Landscaping",
      "Cleaning",
    ],
    painPoints: [
      "Properties sit listed without follow-up",
      "Missed calls from interested buyers",
      "No automated showing reminders",
      "Lead follow-up is inconsistent",
      "Competitors respond faster to inquiries",
      "Client communication falls through cracks",
    ],
    solutions: [
      "AI answers calls 24/7, qualifies buyers, books showings automatically",
      "Auto-SMS reminders to buyers before showings reduce no-shows by 40%",
      "Auto-nurture prospects with property updates and personalized messages",
      "Answer buyer questions instantly, schedule tours without manual work",
    ],
    automations: [
      "Inbound call handling with AI agents",
      "WhatsApp chatbot for property inquiries",
      "Showing reminders via SMS",
      "Lead follow-up sequences",
    ],
  },
  {
    slug: "e-commerce",
    title: "E-Commerce",
    subNiches: [
      "Amazon",
      "Shopify",
      "Dropshipping",
      "Wholesale",
      "Marketplace",
      "B2C",
      "Retail",
      "Fashion",
      "Electronics",
      "Niche",
    ],
    painPoints: [
      "Inventory changes manually across platforms",
      "Competitors undercut prices but you don't know",
      "Customer inquiries answered slowly",
      "No automated reorder reminders",
      "Refunds and returns handled manually",
      "Product listings outdated on multiple sites",
    ],
    solutions: [
      "Auto-track competitor prices and alert you when you're undercut",
      "Update inventory across all platforms in real-time, zero manual work",
      "AI answers product questions, processes returns, handles complaints",
      "Auto-remind customers of past purchases to boost repeat sales",
    ],
    automations: [
      "Price monitoring and competitor tracking",
      "Inventory sync across marketplaces",
      "Customer service chatbot",
      "Reorder reminder campaigns",
    ],
  },
  {
    slug: "saas",
    title: "SaaS",
    subNiches: [
      "Founders",
      "Startups",
      "B2B",
      "Productivity",
      "Analytics",
      "CRM",
      "Marketplace",
      "Tools",
      "Platforms",
      "Enterprise",
    ],
    painPoints: [
      "Leads stuck in pipeline with no follow-up",
      "Trial users don't get onboarded properly",
      "Churn happens because no one checks in",
      "Customer data scattered across tools",
      "Support tickets pile up unanswered",
      "Billing and payment reminders are manual",
    ],
    solutions: [
      "AI sequences nurture leads through sales pipeline automatically",
      "Auto-send onboarding videos, guides, and check-ins to trial users",
      "AI detects inactive users and auto-sends re-engagement campaigns",
      "AI handles common support tickets 24/7, escalates complex issues",
    ],
    automations: [
      "Lead nurture sequences",
      "Trial user onboarding flows",
      "Churn detection and prevention",
      "Support ticket automation",
    ],
  },
  {
    slug: "professional-services",
    title: "Professional Services",
    subNiches: [
      "Consultants",
      "Designers",
      "Developers",
      "Writers",
      "Copywriters",
      "Coaches",
      "Photographers",
      "Videographers",
      "Architects",
      "Engineers",
    ],
    painPoints: [
      "Client proposals take forever to send",
      "Follow-up on quotes is inconsistent",
      "Contracts and documents managed manually",
      "Invoice reminders are forgotten",
      "Client communication is disorganized",
      "Time tracking and billing are error-prone",
    ],
    solutions: [
      "Auto-generate and send professional proposals in minutes, not hours",
      "AI automatically follows up on pending quotes, increases close rate",
      "Auto-send payment reminders, reduce late payments and follow-ups",
      "Auto-organize contracts and files, send for e-signature automatically",
    ],
    automations: [
      "Proposal generation workflows",
      "Quote follow-up sequences",
      "Invoice reminder automation",
      "Document management and e-signature",
    ],
  },
  {
    slug: "healthcare-dental",
    title: "Healthcare & Dental",
    subNiches: [
      "Dentists",
      "Clinics",
      "Therapists",
      "Dermatologists",
      "Surgeons",
      "Pharmacies",
      "Hospitals",
      "Wellness",
      "Mental Health",
      "Pediatric",
    ],
    painPoints: [
      "Patients forget appointments and don't show",
      "Bad reviews scare away new patients",
      "Missed after-hours calls go to competitors",
      "No follow-up on treatment plans",
      "Patients disappear and never return",
      "Staff wastes time on manual reminders",
    ],
    solutions: [
      "WhatsApp reminders 24hrs before appointments cut no-shows in half",
      "Auto-collect reviews after visits, boost your Google rating",
      "AI answers calls after hours, schedules appointments automatically",
      "Auto-follow-up with treatment plans and payment options",
    ],
    automations: [
      "Appointment reminder system via WhatsApp/SMS",
      "Review collection and request automation",
      "After-hours inbound call handling",
      "Treatment plan follow-up sequences",
    ],
  },
  {
    slug: "beauty-fitness",
    title: "Beauty & Fitness",
    subNiches: [
      "Gyms",
      "Salons",
      "Spas",
      "Personal Trainers",
      "Yoga",
      "Studios",
      "Hair",
      "Makeup",
      "Wellness",
      "CrossFit",
    ],
    painPoints: [
      "Members cancel without being asked to stay",
      "Class bookings are chaos without a system",
      "No reminders so members forget sessions",
      "New member onboarding is weak",
      "Reviews aren't collected automatically",
      "Upsells and packages go unnoticed",
    ],
    solutions: [
      "AI reaches out before cancellation, saves memberships automatically",
      "Auto-manage class bookings, send confirmations and reminders",
      "SMS reminders reduce no-shows and boost attendance",
      "Auto-send onboarding flows to new members with intro classes",
    ],
    automations: [
      "Churn prevention workflows",
      "Class booking and confirmation system",
      "Member reminder automations",
      "New member onboarding sequences",
    ],
  },
  {
    slug: "accounting-law-insurance",
    title: "Accounting, Law & Insurance",
    subNiches: [
      "Accountants",
      "CPAs",
      "Lawyers",
      "Insurance Agents",
      "Tax",
      "Compliance",
      "Audit",
      "Legal",
      "Claims",
      "Policies",
    ],
    painPoints: [
      "Document requests take forever to process",
      "Clients miss important deadlines",
      "Invoice follow-ups are manual and forgotten",
      "Compliance reminders aren't automated",
      "New client onboarding is tedious",
      "Communication gaps cause missed opportunities",
    ],
    solutions: [
      "Auto-request documents, organize them, track completion status",
      "AI sends deadline reminders before important dates",
      "Auto-send invoices and payment reminders, reduce late payments",
      "Compliance check reminders for tax deadlines and filings",
    ],
    automations: [
      "Document request and collection workflows",
      "Deadline reminder system",
      "Invoice and payment automation",
      "Compliance calendar automation",
    ],
  },
  {
    slug: "hospitality-food",
    title: "Hospitality & Food",
    subNiches: [
      "Restaurants",
      "Cafes",
      "Hotels",
      "Catering",
      "Bars",
      "Bakeries",
      "Food Trucks",
      "Events",
      "Venues",
      "Resorts",
    ],
    painPoints: [
      "Reservations are missed or double-booked",
      "No-shows hurt revenue constantly",
      "Customer feedback isn't collected",
      "Repeat customers don't get special treatment",
      "Marketing campaigns are sent manually",
      "Staff scheduling is a nightmare",
    ],
    solutions: [
      "AI manages reservations, prevents double-booking, confirms bookings",
      "SMS reminders the day before cut no-shows significantly",
      "Auto-send review requests after each visit",
      "Auto-send loyalty offers to repeat customers",
    ],
    automations: [
      "Reservation management and confirmation",
      "No-show prevention reminders",
      "Review request automation",
      "Loyalty and repeat customer campaigns",
    ],
  },
  {
    slug: "education-coaching",
    title: "Education & Coaching",
    subNiches: [
      "Tutors",
      "Online Courses",
      "Bootcamps",
      "Life Coaches",
      "Business Coaches",
      "Language",
      "Music",
      "Fitness",
      "Mentoring",
      "Workshops",
    ],
    painPoints: [
      "Students miss classes with no reminder",
      "Payment reminders are forgotten",
      "Student progress tracking is manual",
      "New student onboarding is slow",
      "Upsells on courses aren't automated",
      "Communication with students is inconsistent",
    ],
    solutions: [
      "Auto-send class reminders, reduce no-shows and dropouts",
      "AI reminds students of upcoming payments, reduces churn",
      "Auto-track progress and send personalized feedback",
      "Automated onboarding sequence gets new students started fast",
    ],
    automations: [
      "Class reminder system",
      "Payment reminder workflows",
      "Progress tracking automation",
      "New student onboarding sequences",
    ],
  },
  {
    slug: "recruitment",
    title: "Recruitment & Staffing",
    subNiches: [
      "Recruiters",
      "Agencies",
      "HR",
      "Headhunters",
      "Tech Talent",
      "Executive",
      "Temp Staff",
      "Remote",
      "Freelance",
      "Contract",
    ],
    painPoints: [
      "Candidates go cold without follow-up",
      "Job postings don't get shared everywhere",
      "Interview scheduling is back-and-forth chaos",
      "Rejected candidates aren't notified",
      "Onboarding paperwork piles up",
      "You lose candidates to faster competitors",
    ],
    solutions: [
      "AI automatically follows up with candidates at each stage",
      "Job posts shared across LinkedIn, Indeed, and all platforms automatically",
      "AI coordinates interview scheduling, sends confirmations",
      "Auto-send rejection emails and keep candidates in pipeline",
    ],
    automations: [
      "Candidate follow-up sequences",
      "Job posting distribution automation",
      "Interview scheduling and confirmation",
      "Candidate relationship management",
    ],
  },
  {
    slug: "manufacturing-logistics",
    title: "Manufacturing & Logistics",
    subNiches: [
      "Manufacturers",
      "Warehousing",
      "Supply Chain",
      "Distribution",
      "Shipping",
      "Freight",
      "Ecommerce Fulfillment",
      "3PL",
      "Inventory",
      "Orders",
    ],
    painPoints: [
      "Inventory changes aren't synced in real time",
      "Orders get lost in manual processing",
      "Supplier communication is delayed",
      "Shipment tracking is fragmented",
      "Invoicing and payments are slow",
      "Data entry errors cause costly mistakes",
    ],
    solutions: [
      "Real-time inventory sync across all systems, no manual updates",
      "Auto-process orders, eliminate manual data entry errors",
      "Auto-send orders to suppliers and get status updates",
      "AI tracks shipments and alerts customers automatically",
    ],
    automations: [
      "Inventory sync automation",
      "Order processing workflows",
      "Supplier order and communication automation",
      "Shipment tracking and customer alerts",
    ],
  },
  {
    slug: "automotive",
    title: "Automotive Dealerships",
    subNiches: [
      "Dealerships",
      "Service Centers",
      "Used Cars",
      "New Cars",
      "Parts",
      "Mechanic Shops",
      "Detailing",
      "Rentals",
      "Leasing",
      "Trade-in",
    ],
    painPoints: [
      "Service appointment reminders aren't sent",
      "Leads from website inquiries go cold",
      "Test drive follow-ups are forgotten",
      "Customer service requests pile up",
      "Trade-in valuations are slow",
      "Repeat customers don't get contacted",
    ],
    solutions: [
      "SMS reminders for service appointments reduce no-shows",
      "AI immediately follows up with website leads, books test drives",
      "Auto-follow-up after test drives with personalized offers",
      "AI handles customer inquiries instantly via chatbot",
    ],
    automations: [
      "Service appointment reminder system",
      "Lead qualification and follow-up",
      "Test drive confirmation and follow-up",
      "Customer inquiry chatbot",
    ],
  },
  {
    slug: "others",
    title: "Others",
    subNiches: [
      "Construction",
      "Events",
      "Travel",
      "Nonprofits",
      "Creators",
      "Influencers",
      "Local Businesses",
      "Franchises",
      "Car Rentals",
      "Studios",
    ],
    painPoints: [
      "Too much repetitive admin work every day",
      "Customers wait too long for replies",
      "Leads are missed outside working hours",
      "Staff spends hours updating spreadsheets manually",
      "Bookings and inquiries are difficult to manage",
      "Business growth slows because operations are manual",
    ],
    solutions: [
      "AI replies instantly to customer questions 24/7",
      "Automatically organize inquiries, bookings and leads in one place",
      "Send reminders and follow-ups without manual work",
      "Reduce repetitive admin tasks that waste staff time",
      "Connect all your apps and systems together automatically",
      "Save hours every week by automating repetitive tasks",
    ],
    automations: [
      "WhatsApp and website chatbots",
      "Automatic booking and reminder systems",
      "Lead collection and follow-up workflows",
      "Custom business dashboards",
      "Spreadsheet and admin task automation",
      "App integrations and workflow automations",
    ],
  },
];

export const pricing = [
  {
    title: "WhatsApp Bots",
    price: "$200 – $300",
    desc: "Automatic replies for customers, bookings, FAQs and lead responses on WhatsApp.",
    advantage: "You won&apos;t have to reply to customers manually all day.",
  },

  {
    title: "CRM Automations",
    price: "$300 – $500",
    desc: "Automatic follow-ups, reminders and lead organization.",
    advantage: "You won&apos;t need to follow up with leads manually.",
  },

  {
    title: "Lead Capture Systems",
    price: "$350 – $500",
    desc: "Collect leads from ads, websites and forms automatically.",
    advantage: "You won&apos;t lose leads from missed messages or forms.",
  },

  {
    title: "Voice Calling Systems",
    price: "$300 – $500",
    desc: "AI phone callers for bookings, support and follow-ups.",
    advantage: "Your business can answer calls even when you&apos;re busy.",
  },

  {
    title: "Website Chatbots",
    price: "$200 – $300",
    desc: "Chatbots that answer customer questions instantly.",
    advantage: "Customers get replies instantly without waiting for staff.",
  },

  {
    title: "GoHighLevel Automations",
    price: "$300 – $600",
    desc: "Automatic texts, emails and reminders inside GHL.",
    advantage: "You won&apos;t have to send reminders or follow-ups manually.",
  },

  {
    title: "Cold Email Systems Setups",
    price: "$800 – $1,000",
    desc: "Automatic outreach emails with follow-ups.",
    advantage: "Reach more people without manually sending emails daily.",
  },

  {
    title: "LinkedIn Automations",
    price: "$250 – $400",
    desc: "Automatic LinkedIn outreach and messaging.",
    advantage:
      "You won&apos;t have to spend hours messaging prospects manually.",
  },

  {
    title: "Lead Research Workflows",
    price: "$300 – $1,500",
    desc: "Automatically find and organize potential customers.",
    advantage: "You won&apos;t waste time searching for leads manually.",
  },

  {
    title: "Content Posting Systems",
    price: "$400 – $1,000",
    desc: "Automatically create and post social media content.",
    advantage: "Your pages stay active without daily posting work.",
  },

  {
    title: "Custom Data Scrapers",
    price: "$200 – $600",
    desc: "Collect useful data from websites automatically.",
    advantage: "You won&apos;t have to copy and collect data manually.",
  },

  {
    title: "App Integrations",
    price: "$150 – $500",
    desc: "Connect your apps and tools together automatically.",
    advantage: "Your tools will work together without manual updates.",
  },

  {
    title: "Website Development",
    price: "$500 – $1,500+",
    desc: "Landing Pages, Funnels, SaaS.",
    advantage:
      "Your AI Builder apps isn&apos;t going to build a SaaS for you, trust me.",
  },
];

export const useCases = [
  {
    slug: "lead-generation",
    title: "Lead Generation",
    link: [
      "https://www.loom.com/share/dcba7ae9077b437cb0366df6ccebe5b6",
      "https://www.loom.com/share/81722e64bf494bbd8dfcd8f6c8307bdb",
      "https://www.loom.com/share/622469d897f947768d8f48b7b7ca4d9b",
      "https://www.loom.com/share/6b54192117e9427ebaf6df5f46baf642",
    ],
    tagline: "Get new customers automatically using Tech",
    tools: ["Clay", "Apollo", "LinkedIn", "Email", "Apify"],
    overview:
      "We help you find and reach out to potential customers automatically, so you always have new leads coming in.",
    painPoints: [
      "Finding leads manually takes too much time",
      "Following up with people is inconsistent",
      "Potential customers stop replying",
      "You need more leads without hiring more staff",
    ],
    workflow: [
      "We find the right people for your business automatically",
      "AI gathers useful details about each lead",
      "Personalized emails are sent for you",
      "Interested leads are sent directly to your inbox or CRM",
    ],
    results: [
      "More leads without extra employees",
      "Better reply rates from personalized messages",
      "Less time wasted on cold leads",
      "A steady flow of potential customers",
    ],
  },

  {
    slug: "customer-support",
    title: "Customer Support",
    tagline: "Reply to customers 24/7",
    tools: ["WhatsApp", "Website Chat", "Email", "Voicebot"],
    overview:
      "AI replies to customer questions, handles common issues, and supports your customers even when you're offline.",
    painPoints: [
      "Too many customer messages to manage",
      "Repeating the same answers every day",
      "Customers message after work hours",
      "Slow replies frustrate customers",
    ],
    workflow: [
      "AI learns about your business and services",
      "Customer messages are answered instantly",
      "Important issues are passed to your team",
      "All conversations are saved automatically",
    ],
    results: [
      "Faster customer support",
      "Less pressure on your team",
      "Customers get replies anytime",
      "Fewer missed messages and complaints",
    ],
  },

  {
    slug: "appointment-booking",
    title: "Appointment Booking",
    tagline: "Let AI handle bookings",
    tools: ["WhatsApp", "SMS", "Calendly", "GHL"],
    overview:
      "We automate your booking process so customers can book appointments without endless back-and-forth messages.",
    painPoints: [
      "Booking appointments takes too long",
      "People forget appointments",
      "Leads stop replying while waiting",
      "Scheduling feels messy and manual",
    ],
    workflow: [
      "Customer shows interest through a form or message",
      "AI asks a few questions automatically",
      "Meetings are booked instantly",
      "Automatic reminders are sent before the appointment",
    ],
    results: [
      "More booked calls and meetings",
      "Fewer no-shows",
      "Faster response time",
      "Less manual scheduling work",
    ],
  },

  {
    slug: "review-reputation",
    title: "Review & Reputation",
    tagline: "Get more positive reviews",
    link: [
      "https://www.loom.com/share/64afcaf57db04a6bb5f5d4b1fa2d2be6",
    ],
    tools: ["SMS", "WhatsApp", "Google", "Trustpilot"],
    overview:
      "We help you collect more good reviews from happy customers automatically.",
    painPoints: [
      "Customers forget to leave reviews",
      "Asking manually takes too much effort",
      "Bad reviews hurt your reputation",
      "Competitors have stronger online presence",
    ],
    workflow: [
      "Customers receive review requests automatically",
      "Happy customers are guided to leave reviews",
      "Negative feedback is handled privately",
      "Your team gets notified when needed",
    ],
    results: [
      "More positive reviews",
      "Better online reputation",
      "Higher trust from new customers",
      "Improved visibility on Google",
    ],
  },

  {
    slug: "content-posting",
    title: "Content & Social Posting",
    tagline:
      "Stay active online automatically, create content without doing anything yourself",
    link: [
      "https://www.loom.com/share/891cfefe5b764c33a877b172ae765983",
      "https://www.loom.com/share/f46e315cf85b4c02a9f46ea0eca250ce",
    ],
    tools: ["AI", "Buffer", "OpenAI", "Google Sheets"],
    overview:
      "AI helps create and schedule social media content so your business stays active online consistently.",
    painPoints: [
      "Posting content takes too much time",
      "Running out of content ideas",
      "Social pages become inactive",
      "Creating posts manually every day is exhausting",
    ],
    workflow: [
      "AI creates content ideas for your business",
      "Posts and captions are written automatically",
      "You review and approve content if needed",
      "Posts are scheduled across your platforms",
    ],
    results: [
      "Consistent social media presence",
      "Less time spent creating content",
      "More visibility online",
      "Better engagement with your audience",
    ],
  },

  {
    slug: "invoice-payments",
    title: "Invoicing & Payments",
    tagline: "Get paid on time",
    tools: ["Stripe", "QuickBooks", "Email", "SMS"],
    overview:
      "We automate invoices and payment reminders so you spend less time chasing payments.",
    painPoints: [
      "Clients forget to pay invoices",
      "Following up feels awkward",
      "Billing takes too much time",
      "Cash flow becomes inconsistent",
    ],
    workflow: [
      "Invoices are sent automatically",
      "Payment reminders are scheduled for you",
      "Customers can pay instantly online",
      "Payments are tracked automatically",
    ],
    results: [
      "Faster payments",
      "Less awkward follow-ups",
      "Better cash flow",
      "Less admin work every month",
    ],
  },

  {
    slug: "crm-pipeline",
    title: "CRM & Pipeline Automation",
    tagline: "Keep your business organized",
    tools: ["HubSpot", "GHL", "Notion", "Zapier"],
    overview:
      "We automate your CRM so customer information, follow-ups, and sales pipelines stay updated automatically.",
    painPoints: [
      "Your CRM is never updated properly",
      "Leads get forgotten",
      "Too much manual admin work",
      "Tracking sales feels messy",
    ],
    workflow: [
      "Emails, calls, and meetings are logged automatically",
      "Lead stages update automatically",
      "Follow-up reminders are created for your team",
      "Reports are generated automatically",
    ],
    results: [
      "A cleaner and more organized CRM",
      "Fewer missed opportunities",
      "More time for actual sales",
      "Clear visibility into your business",
    ],
  },
];

export function toSlug(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
